name: lint_and_test

on:
 push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: go mod tidy and install
        run: |
          go mod tidy
          make install-go-tools
      - name: build
        run: make build
      - name: testing
        run: make test
