name: lint_and_test

on:
 push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - name: go mod tidy and install
        run: |
          go mod tidy
          make install-go-tools
      - name: build
        run: make build
      - name: testing
        run: make test

  xk6-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: install xk6 lint tools
        run: |
          go install go.k6.io/xk6/cmd/xk6@v1.4.13
          go install github.com/securego/gosec/v2/cmd/gosec@v2.22.10
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
      - name: xk6 lint
        run: xk6 lint
